### ISSUE TITLE
One error happened when I run the En_De_fusion_FC.py.

### ISSUE THREAD

**Issue by 1585231086** [danfenghong/IEEE_TGRS_MDL-RS#1]
Thanks for your open code, but when I run the En_De_fusion_FC.py, there is an error found...detail as follows:

> Traceback (most recent call last):
> 
>   File "xxxx\IEEE_TGRS_MDL-RS-master\MDL-RS_FC-Nets\En_de_fusion_FC.py", line 373, in <module>
>     parameters, val_acc, feature = train_mynetwork(HSI_TrSet, LiDAR_TrSet, HSI_TrSet, LiDAR_TrSet, HSI_TeSet, LiDAR_TeSet, Y_train, Y_test, 'MML')
> 
>   File "xxxx\IEEE_TGRS_MDL-RS-master\MDL-RS_FC-Nets\En_de_fusion_FC.py", line 291, in train_mynetwork
>     minibatches = random_mini_batches(x1_train_set, x2_train_set, x1_train_set_full, x2_train_set_full, y_train_set, minibatch_size, seed)
> 
> TypeError: random_mini_batches() takes 5 positional arguments but 7 were given

How to deal with the situation?

**Comment by danfenghong** [comment]
Hi,

Many thanks for helping us find the potential errors. We have fixed it and
updated the codes in the Github page.
Thanks again.
Bests,
Danfeng

1585231086 <notifications@github.com> 于2020年9月10日周四 下午3:57写道：
